/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

float *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->x + argp->y;

	return &result;
}

float *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->x - argp->y;

	return &result;
}

float *
mul_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->x * argp->y;

	return &result;
}

float *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp->x / argp->y;

	return &result;
}
