/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host, float x, float y, int op)
{
	CLIENT *clnt;
	float  *result_1;
	numbers  add_1_arg;
	float  *result_2;
	numbers  sub_1_arg;
	float  *result_3;
	numbers  mul_1_arg;
	float  *result_4;
	numbers  div_1_arg;
	add_1_arg.x = x;
	add_1_arg.y = y;
	sub_1_arg.x = x;
        sub_1_arg.y = y;
	mul_1_arg.x = x;
        mul_1_arg.y = y;
	div_1_arg.x = x;
        div_1_arg.y = y;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, VERSION1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(op){
		case 1:	{
			result_1 = add_1(&add_1_arg, clnt);
			if (result_1 == (float *) NULL) {
				clnt_perror (clnt, "call failed");
			}else{
				printf("Resultat = %.2f\n", *result_1);	
			}
			break;
		}
		case 2: {
                        result_2 = sub_1(&sub_1_arg, clnt);
                        if (result_2 == (float *) NULL) {
                                clnt_perror (clnt, "call failed");
                        }else{
				printf("Resultat = %.2f\n", *result_2);
			}
			break;
                }
		case 3: {
                        result_3 = mul_1(&mul_1_arg, clnt);
                        if (result_3 == (float *) NULL) {
                                clnt_perror (clnt, "call failed");
                        }else{
				printf("Resultat = %.2f\n", *result_3);
			}
			break;
                }
		case 4: {
                        result_4 = div_1(&div_1_arg, clnt);
                        if (result_4 == (float *) NULL) {
                                clnt_perror (clnt, "call failed");
                        }else{
				printf("Resultat = %.2f\n", *result_4);
			}
			break;
                }default:{
			printf("Argument invalide!\n");
			exit(-1);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int op;

	if (argc < 3) {
		printf ("Usage: %s server_host NUMBER NUMBER\n", argv[0]);
		exit (1);
	}
	printf("==================================\n");
	printf("\t\t1-Addition\n");
	printf("\t\t2-Soustraction\n");
	printf("\t\t3-Multiplication\n");
	printf("\t\t4-Division\n");
	printf("==================================\n");
	printf("Choisir l'operation a faire: ");
	scanf("%d",&op);
	host = argv[1];
	add_prog_1 (host, atof(argv[2]), atof(argv[3]), op);
exit (0);
}

